# 项目相关配置
ruoyi:
  # 名称
  name: ZhangYi
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2019
  # 文件路径
  profile: F:\images
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 9627
  ssl:
    key-store: classpath:httpsKey.p12
    key-alias: ssohttps
    key-store-password: 123456
  servlet:
    # 应用的访问路径
    context-path: /sso
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  # 设定HttpHeader请求头大小
  max-http-header-size: 102400000
 
# 日志配置
#logging:
#  level:
#    com.zy.zy_sso: debug
#    org.springframework: warn
#    org.springframework.web: TRACE
# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #发送邮件
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1073988580@qq.com
    password: mtfqotlxsystbadb
  #rabbitMQ
  application:
    name: spirng-boot-rabbitmq-sender
  rabbitmq:
    host: 47.107.233.154
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost


# MyBatis
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.ruoyi.project
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath:mybatis/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
#shiro:
#  user:
#    # 登录地址
#    loginUrl: /login
#    # 权限认证失败地址
#    unauthorizedUrl: /unauth
#    # 首页地址
#    indexUrl: /index
#    # 验证码开关
#    captchaEnabled: true
#    # 验证码类型 math 数组计算 char 字符
#    captchaType: math
#  cookie:
#    # 设置Cookie的域名 默认空，即当前访问的域名
#    domain: 
#    # 设置cookie的有效访问路径
#    path: /
#    # 设置HttpOnly属性
#    httpOnly: true
#    # 设置Cookie的过期时间，天为单位
#    maxAge: 30
#  session:
#    # Session超时时间（默认30分钟）
#    expireTime: 30
#    # 同步session到数据库的周期（默认1分钟）
#    dbSyncPeriod: 1
#    # 相隔多久检查一次session的有效性，默认就是10分钟
#    validationInterval: 10

## 防止XSS攻击
#xss: 
#  # 过滤开关
#  enabled: true
#  # 排除链接（多个用逗号分隔）
#  excludes: /system/notice/*
#  # 匹配链接
#  urlPatterns: /system/*,/monitor/*,/tool/*
#
## 代码生成
#gen: 
#  # 作者
#  author: ruoyi
#  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
#  packageName: com.ruoyi.project.system
#  # 自动去除表前缀，默认是true
#  autoRemovePre: true
#  # 表前缀(类名不会包含表前缀)
#  tablePrefix: sys_