server:
  port: 5670

#spring.application.narne=rabbitrmq-hello
spring:
  #Rabbitmq\u914D\u7F6E
  rabbitmq:
    host: 47.107.233.154
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    #\u6D88\u606F\u53D1\u9001\u548C\u63A5\u6536\u786E\u8BA4
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

  #redis
  redis:
    database: 0
    host: 47.107.233.154
    password: redis_123456
    port: 6379


