server:
  port: 9002
spring:
  application:
    name: spring-cloud-consumer

#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-consumer
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://pre1:8001/eureka/,http://pre2:8002/eureka/
#注册中心指向end

#开启熔断
feign:
  hystrix:
    enabled: true