

server:
  port: 9004
spring:
  application:
    name: spring-cloud-zuul


  #redis
  redis:
    database: 0
    host: 47.107.233.154
    password: redis_123456
    port: 6379

#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-zuul
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://pre1:8001/eureka/,http://pre2:8002/eureka/
#注册中心指向end

zuul:
  routes:
    api-a:
      path: /spring-cloud-common/**
      serviceId: spring-cloud-common
    api-b:
      path: /spring-cloud-common-login/**
      serviceId: spring-cloud-common-login
    api-c:
      path: /spring-cloud-common-thirdparty/**
      serviceId: spring-cloud-common-thirdparty


