spring:
  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://127.0.0.1:3306/jdbc?useSSL=false&useUnicode=yes&characterEncoding=utf8
    username: root
    password: 123456
    url: jdbc:mysql://47.102.135.231:3306/jdbc?useSSL=false&useUnicode=yes&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    initialization-mode: always
    #schema: 
    # - classpath:sql/department.sql
    # - classpath:sql/employee.sql
  #jpa:
  #  hibernate:
    #更新或者创建数据表结构
   #   ddl-auto: update
    #show-sql: true
    
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com:
      zy:
        dao: debug
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  