server:
  port: 8001
spring:
  application:
    name: eureka
#  profiles:
#    active: pre1
#spring:
#  security:
#    basic:
#        enable: true
#    user:
#        name: admin
#        password: 1234
#    profiles: 127.0.0.1
eureka:
  server:
    enable-self-preservation: false #关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除
  instance:
    hostname: pre1
#    hostname: 127.0.0.1
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
#      defaultZone: http://127.0.0.1:8002/eureka/
      defaultZone: http://pre2:8002/eureka/


###############################################################################

#server:
#  port: 8891
#spring:
#  application:
#    name: eureka
#  profiles:
#    active: pre2
##spring:
##  security:
##    basic:
##        enable: true
##    user:
##        name: admin
##        password: 1234
##    profiles: 127.0.0.1
#eureka:
#  instance:
#    hostname: pre2
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
#      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://pre1:8890/eureka/


########################################################################

#server:
#  port: 8890
#spring:
#  application:
#    name: eureka
#  profiles:
#    active: pre1
##spring:
##  security:
##    basic:
##        enable: true
##    user:
##        name: admin
##        password: 1234
##    profiles: 127.0.0.1
#eureka:
#  instance:
#    hostname: pre1
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
##            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
##      defaultZone: http://pre2:8891/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
