foo: config-client1-test.yml

##注册中心指向start
#eureka:
#    instance:
#        instance-id: config-client
#        appname: config-client
#    client:
#        service-url:
#            defaultZone: http://pre1:8001/eureka/,http://pre2:8002/eureka/
##注册中心指向end