#启动2次，表示两个实例，方便测试负载均衡
server:
#  port: 9003
  port: 9004


spring:
  application:
    name: spring-cloud-common

#注册中心指向start    
eureka:
  #  instance:
  #    instance-id: spring-cloud-common
  #    appname: ${spring.application.name}
  client:
    service-url:
      #      defaultZone: http://admin:1234@127.0.0.1:8890/eureka/,http://admin:1234@127.0.0.1:8891/eureka/
      defaultZone: http://pre1:8001/eureka/,http://pre2:8002/eureka/
#注册中心指向end
