server:
  port: 8010

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/ZhangYi520/SpringCloud.git
          #配置仓库路径
          searchPaths: globalconfig
          #访问git仓库的用户名
          username: ZhangYi520
          #访问git仓库的用户密码
          password: zzzyyy000
      #配置仓库的分支
      label: master

#注册中心指向start
eureka:
  instance:
    instance-id: config-server
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://pre1:8001/eureka/,http://pre2:8002/eureka/
#注册中心指向end